name: 'Test All Packages'

on:
  push:

permissions:
  contents: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout needed for local composite file.
      - uses: actions/checkout@v3
      # Run local composite test.
      - name: 'Test Packages'
        uses: ./.github/actions/run-tests
      # Dry run publish.
      - name: 'Test Publish'
        uses: ./.github/actions/release-jsr-packages
        with:
          dry-run: true
      # TODO: NPM publish dry run.
      



      
